server:
#  ssl:
#    key-store: springboot.p12
#    key-store-password: password
#    key-store-type: pkcs12
#    key-alias: springboot
#    key-password: password
  port: 3001
logging:
  level:
    org:
      springframework:
        security: DEBUG