server:
  port: 3002
logging:
  level:
    org:
      sprngframework:
        security:DEBUG:
spring:
  security:
    oauth2:
      resourceserver:
        opaque:
          introspection-uri: http://localhost:3001/introspect
          introspection-client-id: some-cc-client-id
          introspection-client-secret: some-cc-client-secret