app:
  aws:
    region: "us-east-1"
    secrets:
     dbSecretId: "Spider/rx-powet/db-normal-user-secret"
server:
  port: 3003
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-server:3001/oauth2/jwks