name: Veify

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: boolean
        default: false
      working-directory:
        required: true
        type: boolean
        default: false

jobs:
    reusable_workflow_job:
      runs-on: ubuntu-latest
      environment: production
      steps:  
        - name: abcd    
          working-directory: ${{inputs.working-directory}}
          run: |
            echo "Running mvn test"
            echo ${{github.event_name}}
            echo ${{inputs.config-path}}
  